---

- name: Nextcloud - Send docker-compose.yml and env templates.
  ansible.builtin.template:
    src: "{{ item.template_name }}"
    dest: "{{ nextcloud_basepath }}/{{ item.config_name }}"
    owner: docker
    group: docker
    mode: '0700'
  loop: 
    - { template_name: env.j2, config_name: .env }
    - { template_name: docker-compose.yml.j2, config_name: docker-compose.yml }
    - { template_name: create_db_dump.sh.j2, config_name: create_db_dump.sh }