---

- name: Create directories for bind volumes
  file:
    path: "{{ nextcloud_basepath }}/{{ item }}"
    state: directory
    owner: docker
    group: docker
    mode: '0700'
  loop:
    - nextcloud
    - apps
    - config
    - db
    - data
