---

- name: Nextcloud - Create basepath.
  file:
    path: "{{ nextcloud_basepath }}"
    state: directory
    owner: docker
    group: docker
    mode: '0700'

- name: Nextcloud - Create directories for bind volumes.
  file:
    path: "{{ nextcloud_basepath }}/{{ item.name }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '0775'
  loop:
    - { owner: www-data, group: root, name: nextcloud }
    - { owner: www-data, group: root, name: apps }
    - { owner: www-data, group: root, name: config }
    - { owner: 999, group: root, name: db }
