---

- name: Nextcloud - Create basepath.
  file:
    path: "{{ nextcloud_basepath }}"
    state: directory
    owner: docker
    group: docker
    mode: '0700'

- name: Nextcloud - Create directories for bind volumes.
  file:
    path: "{{ nextcloud_basepath }}/{{ item.name }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '0700'
  loop:
    - { name: nextcloud, onwer: www-data, group: root }
    - { name: apps, onwer: www-data, group: root }
    - { name: config, onwer: www-data, group: root }
    - { name: db, owner: 999, group: root }
