---

- name: Create directories for bind volumes
  file:
    path: "{{ nextcloud_basepath }}/{{ item }}"
    state: directory
    owner: "{{ nextcloud_user_uid }}"
    group: "{{ nextcloud_user_gid }}"
    mode: '0700'
  loop:
    - nextcloud
    - apps
    - config
    - db
